# Generated by Django 5.0.7 on 2024-08-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='classific',
            new_name='classif',
        ),
    ]
